name: ecommerce
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  dartz: ^0.10.1
  get_it: ^9.0.5
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  equatable: ^2.0.0
  go_router: ^17.0.0
  flutter_svg: ^2.2.3
  email_validator: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - ./assets/
